# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distributed_pb2 as distributed__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in distributed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Node service for inter-node communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
                '/distributed_system.NodeService/SendRequest',
                request_serializer=distributed__pb2.RequestMessage.SerializeToString,
                response_deserializer=distributed__pb2.ReplyMessage.FromString,
                _registered_method=True)
        self.SendAccept = channel.unary_unary(
                '/distributed_system.NodeService/SendAccept',
                request_serializer=distributed__pb2.AcceptMessage.SerializeToString,
                response_deserializer=distributed__pb2.AcceptedMessage.FromString,
                _registered_method=True)
        self.SendCommit = channel.unary_unary(
                '/distributed_system.NodeService/SendCommit',
                request_serializer=distributed__pb2.CommitMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendPrepare = channel.unary_unary(
                '/distributed_system.NodeService/SendPrepare',
                request_serializer=distributed__pb2.PrepareMessage.SerializeToString,
                response_deserializer=distributed__pb2.PreparedMessage.FromString,
                _registered_method=True)
        self.SendCommit2PC = channel.unary_unary(
                '/distributed_system.NodeService/SendCommit2PC',
                request_serializer=distributed__pb2.Commit2PCMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendAbort2PC = channel.unary_unary(
                '/distributed_system.NodeService/SendAbort2PC',
                request_serializer=distributed__pb2.Abort2PCMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendAcknowledgment = channel.unary_unary(
                '/distributed_system.NodeService/SendAcknowledgment',
                request_serializer=distributed__pb2.AcknowledgmentMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendFail = channel.unary_unary(
                '/distributed_system.NodeService/SendFail',
                request_serializer=distributed__pb2.FailMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendRecover = channel.unary_unary(
                '/distributed_system.NodeService/SendRecover',
                request_serializer=distributed__pb2.RecoverMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendLeaderFailed = channel.unary_unary(
                '/distributed_system.NodeService/SendLeaderFailed',
                request_serializer=distributed__pb2.FailMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendNewView = channel.unary_unary(
                '/distributed_system.NodeService/SendNewView',
                request_serializer=distributed__pb2.NewViewMessage.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendPrepareElection = channel.unary_unary(
                '/distributed_system.NodeService/SendPrepareElection',
                request_serializer=distributed__pb2.PrepareElectionMessage.SerializeToString,
                response_deserializer=distributed__pb2.PromiseMessage.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/distributed_system.NodeService/GetBalance',
                request_serializer=distributed__pb2.BalanceRequest.SerializeToString,
                response_deserializer=distributed__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.GetAllBalances = channel.unary_unary(
                '/distributed_system.NodeService/GetAllBalances',
                request_serializer=distributed__pb2.Empty.SerializeToString,
                response_deserializer=distributed__pb2.AllBalancesResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/distributed_system.NodeService/Flush',
                request_serializer=distributed__pb2.Empty.SerializeToString,
                response_deserializer=distributed__pb2.Empty.FromString,
                _registered_method=True)
        self.SendReshard = channel.unary_unary(
                '/distributed_system.NodeService/SendReshard',
                request_serializer=distributed__pb2.ReshardMessage.SerializeToString,
                response_deserializer=distributed__pb2.ReshardResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Node service for inter-node communication
    """

    def SendRequest(self, request, context):
        """Client requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAccept(self, request, context):
        """Multi-Paxos messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrepare(self, request, context):
        """Two-Phase Commit messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommit2PC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAbort2PC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAcknowledgment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFail(self, request, context):
        """Control messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRecover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLeaderFailed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNewView(self, request, context):
        """Leader election (bonus feature)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrepareElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Utility RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendReshard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRequest,
                    request_deserializer=distributed__pb2.RequestMessage.FromString,
                    response_serializer=distributed__pb2.ReplyMessage.SerializeToString,
            ),
            'SendAccept': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAccept,
                    request_deserializer=distributed__pb2.AcceptMessage.FromString,
                    response_serializer=distributed__pb2.AcceptedMessage.SerializeToString,
            ),
            'SendCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommit,
                    request_deserializer=distributed__pb2.CommitMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendPrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrepare,
                    request_deserializer=distributed__pb2.PrepareMessage.FromString,
                    response_serializer=distributed__pb2.PreparedMessage.SerializeToString,
            ),
            'SendCommit2PC': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommit2PC,
                    request_deserializer=distributed__pb2.Commit2PCMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendAbort2PC': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAbort2PC,
                    request_deserializer=distributed__pb2.Abort2PCMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendAcknowledgment': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAcknowledgment,
                    request_deserializer=distributed__pb2.AcknowledgmentMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendFail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFail,
                    request_deserializer=distributed__pb2.FailMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRecover,
                    request_deserializer=distributed__pb2.RecoverMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendLeaderFailed': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLeaderFailed,
                    request_deserializer=distributed__pb2.FailMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendNewView': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNewView,
                    request_deserializer=distributed__pb2.NewViewMessage.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendPrepareElection': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrepareElection,
                    request_deserializer=distributed__pb2.PrepareElectionMessage.FromString,
                    response_serializer=distributed__pb2.PromiseMessage.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=distributed__pb2.BalanceRequest.FromString,
                    response_serializer=distributed__pb2.BalanceResponse.SerializeToString,
            ),
            'GetAllBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBalances,
                    request_deserializer=distributed__pb2.Empty.FromString,
                    response_serializer=distributed__pb2.AllBalancesResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=distributed__pb2.Empty.FromString,
                    response_serializer=distributed__pb2.Empty.SerializeToString,
            ),
            'SendReshard': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReshard,
                    request_deserializer=distributed__pb2.ReshardMessage.FromString,
                    response_serializer=distributed__pb2.ReshardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Node service for inter-node communication
    """

    @staticmethod
    def SendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendRequest',
            distributed__pb2.RequestMessage.SerializeToString,
            distributed__pb2.ReplyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAccept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendAccept',
            distributed__pb2.AcceptMessage.SerializeToString,
            distributed__pb2.AcceptedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendCommit',
            distributed__pb2.CommitMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendPrepare',
            distributed__pb2.PrepareMessage.SerializeToString,
            distributed__pb2.PreparedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommit2PC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendCommit2PC',
            distributed__pb2.Commit2PCMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAbort2PC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendAbort2PC',
            distributed__pb2.Abort2PCMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAcknowledgment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendAcknowledgment',
            distributed__pb2.AcknowledgmentMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendFail',
            distributed__pb2.FailMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendRecover',
            distributed__pb2.RecoverMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLeaderFailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendLeaderFailed',
            distributed__pb2.FailMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendNewView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendNewView',
            distributed__pb2.NewViewMessage.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrepareElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendPrepareElection',
            distributed__pb2.PrepareElectionMessage.SerializeToString,
            distributed__pb2.PromiseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/GetBalance',
            distributed__pb2.BalanceRequest.SerializeToString,
            distributed__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/GetAllBalances',
            distributed__pb2.Empty.SerializeToString,
            distributed__pb2.AllBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/Flush',
            distributed__pb2.Empty.SerializeToString,
            distributed__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendReshard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.NodeService/SendReshard',
            distributed__pb2.ReshardMessage.SerializeToString,
            distributed__pb2.ReshardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
